title: Running Reflections
description: An ongoing record of my reactions to new ideas in multidisciplinary teaching
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
